;EasyRC一键装机配置文件,如需启用配置功能,请删除字段的开头符号  ;  分号及删除后面的注释
;其他高级功能请仔细阅读 使用教程文档\技术支持文档.pdf
;部分功能自定义需付费为VIP版,详情请访问http://www.51cxsoft.com/ujyvip/
;请注意本配置文件的文本编码需为 [Ansi] 编码
[Config]
;Search=1 ;1为仅搜索U盘; 2为仅搜索光盘; 3为仅搜索磁盘; 5为不搜索镜像
;SearchDepth=3 ;定义程序扫描镜像文件的目录深度,默认为3
;Url=您需捆绑的首页地址;VIP功能
;WimCore=1 ;定义恢复WIM/ESD/SWM的核心,默认1 为Imagex,2为wimlib-Imagex,3为Dism核心,NT5.X系统不生效
;bootName=Windows一键急救系统
;Title=EasyRC一键装机 ;请查看文档
;VolumeLabel=1 ;0为关闭还原后修改分区卷标名称,其他或留空为默认修改
;Online=1 ;1为关闭在线重装功能,其他或留空为默认显示
;ToolsMenu=1 ;自定义是否显示[扩展工具]功能页,1为关闭显示,其他为显示;VIP功能
;NoSoft=1 ;自定义是否显示[软件大全]功能页,1为关闭显示,其他为显示;VIP功能
;soft= ;0或空为默认捆绑软件/首页,1为默认不捆绑,VIP功能
;restart=1 定义完成后是否自动重启/关机, 1  为完成后不进行重启/关机操作,2为默认关机，其他为默认重启
;AutoInstallOS= 定义是否自动安装Windows,1为不自动安装,2为强制写入自动应答文件,其他默认为不强制写入自动应答文件
;Recovery=1 定义桌面环境是否在恢复系统后默认安装急救系统,1为恢复后安装,2为恢复后安装但在成功进入桌面后清除急救系统,其他为默认不安装
;AllFixBoot=1 ;0或其他为默认不勾选 [全局引导修复],1为勾选
;check=0 ;1为默认还原时校验镜像文件完整性,其他为默认不校验
;BackupDriveLetter=1 ;启用保持原系统盘符功能,1为启用
;UserName=1 ;启用自定义用户名功能,如值为1时则在部署时自动根据当前电脑的品牌厂家名称创建用户名,如为0或空则不启用该功能,其他字符则为在部署时根据自定义名称创建用户名
;SystemYh=1 ;启用更多选项-系统优化调整,1为启用,其他为默认不启用;启用更多选项-系统优化调整[通用]功能,则 Win10JJ=1 失效
;OSRetention=1 ;启用更多选项-禁用Win10保留空间,1为启用,其他为默认不启用
;OSUpdate=1 ;启用更多选项-禁用Windows自动更新,1为启用,其他为默认不启用
;windowsDefender=1 ;启用更多选项-移除 Windows Defender,1为启用,其他为默认不启用
;OSSafe=1 ;启用更多选项-查杀强制捆绑病毒木马,1为启用,其他为默认不启用
;VMD=1 ;1为取消勾选导入11代酷睿存储驱动,其他为默认判断处理器型号
;AutoRunDrv=1 ;1为开启自动加载万能驱动,其他为不加载
;skipcheckTpm=0 ;0为关闭更多选项-[跳过Win11的TPM/CPU校验],其他为默认开启
;skipBitLocker=0 ;0为关闭更多选项-[关闭BitLocker自动加密],其他为默认开启
[Task];VIP功能
;task1=定义程序运行后的运行第三方程序的操作,支持定义恢复后运行、部署中运行、首次进桌面运行、恢复后删除文件、部署中恢复后删除文件、首次进桌面恢复后删除文件,详情看支持文档
[Key] ;自定义导入系统激活key
Win7=
Win8=
Win8.1=
Win10=
Win11=

[WanDrv]在安装系统时通过配置文件自动选择万能驱动,详情请仔细阅读 装机助理支持文档.txt
Win7X86=:\Win7X86\EasyDrv7(Win7.x86).exe
Win7X64=%CurDir%\Win7X64\EasyDrv7(Win7.x64).exe
Win10X64=
Win10X86=
Win8X64=
Win8X86=
Win8.1X86=
Win8.1X64=

[OSInstall]
File=
[OEMInformation]
;Manufacturer=
;SupportURL=
;Model=
;SupportHours=
;SupportPhone=
;RegisteredOrganization=
;RegisteredOwner=